### ISSUE TITLE
Is it possible to stream videos 

### ISSUE THREAD

**Issue by Tibingeo** [nisargjhaveri/WirelessAndroidAutoDongle#193] opened 2024-09-21 07:02 UTC
Hi, current android auto on my XUV 500 does not allow to stream videos thorough youtube or any other means is it possible make it happen thorough the raspberry PI.
Currently I am using Raspberry Pi to connect to android auto wireless.

**Comment by akshayunaik** [comment] 2024-09-24 10:27
No. It is by design that you will not be able to watch videos on Android Auto. This project only allows you to make wired Android Auto to wireless Android Auto using RPi.

**Comment by nisargjhaveri** [comment] 2024-09-24 14:45
As @akshayunaik, this is currently out of scope for this. #47 might be somewhat related though.

**Closed by nisargjhaveri** 2024-09-24 14:45 UTC
