### ISSUE TITLE
Car Wifi Hotspot

### ISSUE THREAD

**Issue by Tonks140** [nisargjhaveri/WirelessAndroidAutoDongle#120] opened 2024-05-22 19:40 UTC
Hi,

My car provides a WIFI hotspot (I believe this has unlimited data), is there anyway I can bridge the two wifi networks (hotspot and AAWireless) using the dongle so that I am not using my phone data?

Thanks

**Comment by nisargjhaveri** [comment] 2024-05-25 13:28
Duplicate of #46.

**Closed by nisargjhaveri** 2024-05-25 13:28 UTC
